
stages:
  - build
  - deploy

make stretch 3.6:
  stage: build
  image: gorialis/discord.py:3.6-stretch-master
  before_script:
    - pip install -U Cython==0.27.3
  script:
    - python ./setup.py bdist_egg bdist_wheel
  artifacts:
    paths:
      - dist
    expire_in: 30 days

make stretch 3.7:
  stage: build
  image: gorialis/discord.py:3.7-stretch-master
  before_script:
    - pip install -U Cython==0.27.3
  script:
    - python ./setup.py bdist_egg bdist_wheel
  artifacts:
    paths:
      - dist
    expire_in: 30 days

make stretch 3.8:
  stage: build
  image: gorialis/discord.py:3.8-stretch-master
  before_script:
    - pip install -U Cython==0.27.3
  script:
    - python ./setup.py bdist_egg bdist_wheel
  artifacts:
    paths:
      - dist
    expire_in: 30 days

accumulate distributions:
  stage: deploy
  image: gorialis/discord.py:3.8-stretch-master
  script:
    - ls dist
  artifacts:
    paths:
      - dist
    expire_in: 30 days
