
version: 2

jobs:
  "make stretch 3.6":
    docker:
      - image: gorialis/discord.py:3.6-stretch-master

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install Cython
          command: |
            pip install -U Cython==0.27.3

      - run:
          name: build distributions
          command: |
            python ./setup.py bdist_egg bdist_wheel

      - store_artifacts:
          path: dist
          destination: distributions

  "make stretch 3.7":
    docker:
      - image: gorialis/discord.py:3.7-stretch-master

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install Cython
          command: |
            pip install -U Cython==0.27.3

      - run:
          name: build distributions
          command: |
            python ./setup.py bdist_egg bdist_wheel

      - store_artifacts:
          path: dist
          destination: distributions

  "make stretch 3.8":
    docker:
      - image: gorialis/discord.py:3.8-stretch-master

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install Cython
          command: |
            pip install -U Cython==0.27.3

      - run:
          name: build distributions
          command: |
            python ./setup.py bdist_egg bdist_wheel

      - store_artifacts:
          path: dist
          destination: distributions

workflows:
  version: 2
  build:
    jobs:
      - "make stretch 3.6"
      - "make stretch 3.7"
      - "make stretch 3.8"
